import { Player, CharStat } from '@/types/Player';
import { CharacterStatItem } from '@/components/CharacterStatItem';

function CharacterStats({ stats }: { stats: CharStat[] }) {
  return (
    <ul>
      {stats.map((stat: CharStat) => (
        <li key={stat.type}>
          <CharacterStatItem stat={stat}/>
        </li>
      ))}
    </ul>
  );
}

export default function PlayerDetails({ player }: { player: Player }) {
  //TODO: add + and - buttons to increase and decrease stats
  return (
    <>
      <div></div>
      <div>
        <p>
          This is some text that will be generated by OpenAI when the character
          is created. Ideally it&apos;s funny and short.
        </p>
        <ul>
          <li>Player Name: {player.name}</li>
          <li>Level: {player.lvl}</li>
          <li>
            Experience: {player.exp} / {player.expToLvlUp}
          </li>
          <li>
            Health: {player.currentHp} / {player.maxHp}
          </li>
        </ul>
        <CharacterStats stats={player.stats} />
      </div>
    </>
  );
}
